---
#need to create fail case

- name: Create cloud config
  template:
    dest: "{{ openshift.common.config_base }}/cloudprovider/openstack.conf"
    src: vsphere.conf.j2
  when: openshift_cloudprovider_vsphere_server is defined and openshift_cloudprovider_vsphere_username is defined and openshift_cloudprovider_vsphere_password is defined and openshift_cloudprovider_vsphere_insecure is defined and openshift_cloudprovider_vsphere_datacenter is defined and openshift_cloudprovider_vsphere_datastore is defined
